urls:
  api:
    - 'https://testnet-microservice.elrond.com'
    - 'https://devnet-microservice.elrond.com'
    - 'https://microservice.elrond.com'
api:
  public: true
  private: true
security:
  jwtSecret: ''